package io.lundie.michael.viewcue.utilities;

public enum DataStatus {
    ATTEMPTING_API_FETCH,
    FETCH_COMPLETE,
    FETCHING_FROM_DATABASE,
    DATABASE_EMPTY,
    ERROR_PARSING,
    ERROR_NETWORK_FAILURE,
    ERROR_UNAVAILABLE_OFFLINE,
    ERROR_NOT_FOUND,
    ERROR_SERVER_BROKEN,
    ERROR_UNKNOWN
}